

namespace TypeToSquad.Model.Settings;


/// <summary>
/// A storage for all user settings.
/// </summary>
/// <remarks>
/// Only fields implementing <see cref="IVariantSavable"/> are saved.
/// Properties are ignored.
/// </remarks>
public record UserSettings {
	
	// ReSharper disable InconsistentNaming
	
	// ===== ===== ===== GENERAL ===== ===== =====

	/// <summary>Whether to show advanced settings.</summary>
	public readonly Field<bool> ShowAdvancedSettings = new(false);

	/// <summary>Whether to enable error notifications from LogMonitor.</summary>
	public readonly Field<bool> EnableErrorNotifications = new(true);
	
	/// <summary>Whether to enable warning notifications from LogMonitor.</summary>
	public readonly Field<bool> EnableWarningNotifications = new(false);


	// ===== ===== ===== VOICE ===== ===== =====

	/// <summary>Key of the current tts voice. Generated by <see cref="DaemonVoiceStorage.VoiceToSelectionKey"/>.</summary>
	public readonly FieldOptionsRuntime VoiceKey = new();

	/// <summary>The volume of the voice.</summary>
	public readonly FieldNumericRange<int> SynthesisVolumePercent = new(0, 100, defaultValue: 100);

	/// <summary>The relative pitch of the voice.</summary>
	public readonly FieldNumericRange<double> VoicePitch = new(0, 2, defaultValue: 1, digitsPrecision: 2);

	/// <summary>The speaking rate (speed multiplier) of the voice.</summary>
	public readonly FieldNumericRange<double> VoiceRate = new(0.5, 6, defaultValue: 1, digitsPrecision: 2);


	// ===== ===== ===== OUTPUT ===== ===== =====

	/// <summary>Name of the current output device.</summary>
	public readonly FieldOptionsRuntime Device = new();

	/// <summary>Max number of outputs played at the same time.</summary>
	public readonly FieldNumericRange<int> MaxConcurrentStreams = new(1, 64, defaultValue: 6);


	// ===== ===== ===== INPUT ===== ===== =====

	/// <summary>Number of previous inputs held in memory.</summary>
	public readonly FieldNumericRange<int> HistorySlots = new(0, short.MaxValue, defaultValue: 32);
	
	/// <summary>Max number of times text substitutions may run.</summary>
	public readonly FieldNumericRange<int> MaxReplacementPasses = new(0, 100, defaultValue: 20);

	/// <summary>A table of text replacements to perform. Patterns are written using regex.</summary>
	public readonly Table<(string pattern, string replacement)> TextReplacements = new(
		() => new Field<string>(""),
		() => new Field<string>("")
	);


	// ===== ===== ===== MARKUP ===== ===== =====
	
	/// <summary>A table of voices change hints and voices they correspond to.</summary>
	public readonly Table<(string hint, string voiceKey)> VoiceChanges = new(
		() => new FieldTagContent(),
		() => new FieldOptionsRuntime()
	);
	
	/// <summary>A table of sound effect hints and file paths they correspond to.</summary>
	/// <remarks>NOT IMPLEMENTED</remarks>
	public readonly Table<(string hint, string path, int volumePercent)> SoundEffects = new(
		() => new FieldTagContent(),
		() => new Field<string>(""),
		() => new FieldNumericRange<int>(0, 100, defaultValue: 100)
	);
	
	/// <summary>A table of custom tags and their content rules.</summary>
	/// <remarks>NOT IMPLEMENTED</remarks>
	public readonly Table<(string type, string pattern, string replacement)> UserTags = new(
		() => new FieldTagContent(disallowWhitespace: true),
		() => new FieldTagContent(),
		() => new Field<string>("")
	);
	
	/// <summary>Whether pressing Tab can open and close tags.</summary>
	public readonly Field<bool> TabToInsertTag = new(true);

	/// <summary>Whether to automatically complete tags during writing.</summary>
	public readonly Field<bool> AutocompleteTags = new(false);
	
}
